### ISSUE TITLE
[ERROR] with "get_csv" imported from opennyai.ner 

### ISSUE THREAD

**Issue by d-saikrishna** [OpenNyAI/Opennyai#1]
### System Information
opennyai 0.0.10
Python 3.9.13
Ubuntu 22.04.1 LTS

### Description
The following code led to an error:
`from opennyai.ner import get_csv
get_csv(ner_doc_1,'sample_judgement1_NER.csv', save_path=r"/home/krishna/NLP_Justice/POCSO/sample_judgement1_NER.csv")`

> ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_27488/2496738980.py in <module>
      1 # Saving NER Results
      2 from opennyai.ner import get_csv
----> 3 get_csv(ner_doc_1,'sample_judgement1_NER.csv', save_path=r"/home/krishna/NLP_Justice/POCSO/sample_judgement1_NER.csv")

~/anaconda3/lib/python3.9/site-packages/opennyai/ner/ner_utils.py in get_csv(doc, f_name, save_path)
     99         label.append('PROVISION')
    100         normalised_entities.append(pro_ent[2] + ' of ' + pro_ent[3])
--> 101     for pre_head in doc.user_data['precedent_clusters'].keys():
    102 
    103         for ent in doc.user_data['precedent_clusters'][pre_head]:

KeyError: 'precedent_clusters'

Same error is repeated when I check for precednet clusters.
`ner_doc_1.user_data['precedent_clusters']`

There are PRECEDENTS entities recognized in the judgement.

**Comment by amant555** [comment]
Hi @d-saikrishna 
I have pushed a fix on git for this issue. You can reinstall the library and try the document again. In case issue still remain please share the file so we can replicate and fix the code.

To install the library from source
```
git clone https://github.com/OpenNyAI/Opennyai.git
cd Opennyai
pip install .
```

In case you're trying to export the identified entities and clusters. It is highly preferred to do that in form of json as json carry all necessary information such as span and normalised entity for each entity .
To do so you can use the code given in our documentation. where we create a pipeline  and it return the json result of that document.
To export that json to a file you can use this sample code:
```
import opennyai.ner as InLegalNER
from opennyai.utils import Data
import urllib

###### Get court judgment texts on which to run the AI models
text1 = urllib.request.urlopen('https://raw.githubusercontent.com/OpenNyAI/Opennyai/master/samples/sample_judgment1.txt').read().decode()
text2 = urllib.request.urlopen('https://raw.githubusercontent.com/OpenNyAI/Opennyai/master/samples/sample_judgment2.txt').read().decode()
texts_to_process = [text1,text2] ### you can also load your text files directly into this
data = Data(texts_to_process)  #### create Data object for data  preprocessing before running ML models

pipeline = Pipeline(components=['NER'], use_gpu=use_gpu, verbose=True,ner_model_name='en_legal_ner_trf',
             ner_mini_batch_size=40000, ner_do_sentence_level=True, ner_do_postprocess=True,
             ner_statute_shortforms_path='')

results = pipeline(data)

# Export the results to a json file
import json
with open('output.json','w') as f:
     json.dumps(results,f,indent=4)
```

**Comment by d-saikrishna** [comment]
Hi @amant555, Thank you for the prompt response.

Yes, there is no error in using "get_csv" after re-installation of the library from github. But, one problem persists:
When I run this `identified_entites = [(ent, ent.label_) for ent in ner_doc_1.ents]`, I can see PRECEDENT entities identified in the judgement text. 

But when I run `InLegalNER.get_unique_precedent_count(ner_doc_1)`, I am unable to see the frequency count of PRECEDENTS. Similarly `ner_doc_1.user_data['precedent_clusters']` throws a null dictionary.

Sharing the judgement copy on which I faced the issue - PFA
[sample.txt](https://github.com/OpenNyAI/Opennyai/files/10495343/sample.txt)
